[project]
name = "langjo"
version = "0.1.0"
description = "CLI journaling tool for language learning"
dependencies = [
    "textual",
    "sudachipy",
    "sudachidict_core",
    "psycopg2-binary",
    "SQLAlchemy",
    "python-dotenv",
    "alembic",
    "fastapi[standard]",
]

[project.scripts]
langjo = "journal.ui.main:main"

[tool.setuptools]
packages = ["journal", "journal.ui"]