"""initial schema

Revision ID: 0c79669e0a14
Revises: 
Create Date: 2026-08-24 15:22:50.404437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c79669e0a14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab')
    op.drop_table('entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('entries_pkey'))
    )
    op.create_table('vocab',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dict_form', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('vocab_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vocab_pkey')),
    sa.UniqueConstraint('dict_form', 'reading', name=op.f('uq_dict_form_reading'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
